# Generated by Django 4.2.7 on 2024-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='username', max_length=150),
            preserve_default=False,
        ),
    ]
