# Generated by Django 4.2.7 on 2024-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_refreshtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
