# Generated by Django 4.2.7 on 2024-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_refreshtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expire_time',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
