# Generated by Django 4.2.7 on 2024-04-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_refreshtoken_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expire_time',
            field=models.DurationField(),
        ),
    ]
